const Joi = require('joi');

module.exports = Joi.object({
  id: Joi.string(), // Generated by Firestore, if not provided
  name: Joi.string().required(),
  info: Joi.string().required(),
  count: Joi.number().integer().min(0).required(),
});
