name: Lint and Auto-Fix

permissions:
  contents: write

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      # Run ESLint without --fix to detect errors. 
      # 'continue-on-error: true' lets us proceed even if lint fails.
      - name: Run ESLint check
        id: lint
        run: npm run lint
        continue-on-error: true
      
      # If ESLint failed, attempt to fix issues automatically.
      - name: Auto-fix Lint Errors
        if: steps.lint.outcome == 'failure'
        run: npm run lint:fix
      
      # If fixes were applied, commit and push them back to the PR branch.
      - name: Commit and push fixes
        if: steps.lint.outcome == 'failure'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # Check if any files have changed after running --fix
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "fix: auto-fix ESLint issues"
            git push origin HEAD:${{ github.event.pull_request.head.ref }}
          fi
