name: Lint and Auto-Fix

permissions:
  contents: write

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      # Run ESLint check and fix
      - name: Run ESLint and auto-fix
        run: |
          npm run lint:fix || true
          # Check if any files have changed
          if [ -n "$(git status --porcelain)" ]; then
            echo "Lint fixes applied. Preparing to commit."
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "fix: auto-fix ESLint issues"
            
            # Handle branch dynamically based on the event type
            if [[ "${{ github.event_name }}" == "pull_request" ]]; then
              git pull --rebase origin ${{ github.event.pull_request.head.ref }}
              git push origin HEAD:${{ github.event.pull_request.head.ref }}
            else
              git pull --rebase origin ${{ github.ref_name }}
              git push origin HEAD:${{ github.ref_name }}
            fi
          else
            echo "No lint fixes required or remaining errors are non-fixable."
          fi
