name: Zero65Tech

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  test:
    uses: Zero65Tech/github-workflows/.github/workflows/npm-test.yaml@master
    with:
      NODE_VERSION: '22' # 22.12.0
  lint:
    needs: test
    uses: Zero65Tech/github-workflows/.github/workflows/lint-and-commit.yaml@master
    with:
      NODE_VERSION: '22' # 22.12.0
  update:
    needs: lint
    uses: Zero65Tech/github-workflows/.github/workflows/update-and-commit.yaml@master
    with:
      NODE_VERSION: '22' # 22.12.0
