name: Zero65Tech

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  test:
    uses: Zero65Tech/github-workflows/.github/workflows/build-test-commit.yaml@master
    with:
      NODE_VERSION: '22' # 22.12.0
